# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: lazyfwd

before:
   hooks:
      - go mod tidy

builds:
   - id: lazyfwd
     main: .
     binary: lazyfwd
     env:
        - CGO_ENABLED=0
     goos:
        - darwin
        - linux
     goarch:
        - amd64
        - arm64
     ldflags:
        - -s -w
        - -X main.version={{.Version}}
        - -X main.commit={{.Commit}}
        - -X main.date={{.Date}}

archives:
   - id: default
     formats:
        - tar.gz
     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
     files:
        - README.md
        - LICENSE
        - src: contrib/lazyfwd.service
          dst: .
          strip_parent: true
        - src: contrib/lazyfwd.plist
          dst: .
          strip_parent: true

checksum:
   name_template: "checksums.txt"
   algorithm: sha256

changelog:
   sort: asc
   filters:
      exclude:
         - "^docs:"
         - "^test:"
         - "^ci:"
         - "Merge pull request"
         - "Merge branch"

homebrew_casks:
   - name: lazyfwd
     repository:
        owner: atas
        name: homebrew-tap
        token: "{{ .Env.TAP_GITHUB_TOKEN }}"
     homepage: "https://github.com/atas/lazyfwd"
     description: "On-demand Kubernetes port forwarding proxy"
     binaries:
        - lazyfwd
     caveats: |
        To run lazyfwd as a background service:
          brew services start lazyfwd

        View service logs:
          tail -f $(brew --prefix)/var/log/lazyfwd.log

        For manual runs:
          lazyfwd

        ⚠️ After running, edit the created 🔴 ~/.lazyfwd.yaml and add your routes!!! ‼️
        Route changes will be picked up automatically.

     # Remove macOS quarantine for unsigned binaries
     hooks:
        post:
           install: |
              system_command "/usr/bin/xattr",
                args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyfwd"]

     # Service definition for brew services
     service: lazyfwd.plist

     # Cleanup on uninstall
     uninstall:
        launchctl:
           - com.atas.lazyfwd

     zap:
        trash:
           - "~/.lazyfwd.yaml"

release:
   github:
      owner: atas
      name: lazyfwd
   draft: false
   prerelease: auto
   name_template: "v{{.Version}}"
