# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: autotunnel

before:
   hooks:
      - go mod tidy

builds:
   - id: autotunnel
     main: .
     binary: autotunnel
     env:
        - CGO_ENABLED=0
     goos:
        - darwin
        - linux
     goarch:
        - amd64
        - arm64
     ldflags:
        - -s -w
        - -X main.version={{.Version}}
        - -X main.commit={{.Commit}}
        - -X main.date={{.Date}}

archives:
   - id: default
     formats:
        - tar.gz
     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
     files:
        - README.md
        - LICENSE
        - src: contrib/autotunnel.service
          dst: .
          strip_parent: true

checksum:
   name_template: "checksums.txt"
   algorithm: sha256

changelog:
   sort: asc
   filters:
      exclude:
         - "^docs:"
         - "^test:"
         - "^ci:"
         - "Merge pull request"
         - "Merge branch"

brews:
   - name: autotunnel
     repository:
        owner: atas
        name: homebrew-tap
        token: "{{ .Env.TAP_GITHUB_TOKEN }}"
     homepage: "https://github.com/atas/autotunnel"
     description: "On-demand Kubernetes port forwarding proxy"
     license: "MIT"
     install: |
        bin.install "autotunnel"
     service: |
        run [opt_bin/"autotunnel"]
        keep_alive true
        log_path var/"log/autotunnel.log"
        error_log_path var/"log/autotunnel.log"
        working_dir var
     caveats: |
        ---------
        To run autotunnel as a background service:
          brew services start autotunnel
        Service logs: 
          tail -f $(brew --prefix)/var/log/autotunnel.log
        For manual runs:
          autotunnel
        ---------
        ⚠️ After running, edit the created 🔴 ~/.autotunnel.yaml and add your routes!!! ‼️
        Route changes will be picked up automatically.
        ---------
        ⭐🌟⭐ Please give the repo a star if useful ⭐🌟⭐
        https://github.com/atas/autotunnel
        ---------
release:
   github:
      owner: atas
      name: autotunnel
   draft: false
   prerelease: auto
   name_template: "v{{.Version}}"
